In [2]:
import pandas as pd

In [8]:
MatHealth = pd.read_csv('https://data.cdc.gov/api/views/nfuu-hu6j/rows.csv?accessType=DOWNLOAD')

In [9]:
MatHealth

,INDICATOR,INDICATOR_NUM,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,ESTIMATE,FLAG
0,"Infant, neonatal, postneonatal, fetal, and per...",1,"Infant deaths per 1,000 live births",1,Total,0,All mothers,0.10,1983,1,10.9,NaN
1,"Infant, neonatal, postneonatal, fetal, and per...",1,"Infant deaths per 1,000 live births",1,Total,0,All mothers,0.10,1985,2,10.4,NaN
2,"Infant, neonatal, postneonatal, fetal, and per...",1,"Infant deaths per 1,000 live births",1,Total,0,All mothers,0.10,1990,3,8.9,NaN
3,"Infant, neonatal, postneonatal, fetal, and per...",1,"Infant deaths per 1,000 live births",1,Total,0,All mothers,0.10,1995,4,7.6,NaN
4,"Infant, neonatal, postneonatal, fetal, and per...",1,"Infant deaths per 1,000 live births",1,Total,0,All mothers,0.10,1996,5,7.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2683,"Infant, neonatal, postneonatal, fetal, and per...",1,"Perinatal deaths per 1,000 live births plus la...",6,Race and Hispanic origin (Single race),4,Not Hispanic or Latina: Asian or Pacific Islander,2.50,2018,27,NaN,...
2684,"Infant, neonatal, postneonatal, fetal, and per...",1,"Perinatal deaths per 1,000 live births plus la...",6,Race and Hispanic origin (Single race),4,Not Hispanic or Latina: Asian,2.51,2017,26,NaN,...
2685,"Infant, neonatal, postneonatal, fetal, and per...",1,"Perinatal deaths per 1,000 live births plus la...",6,Race and Hispanic origin (Single race),4,Not Hispanic or Latina: Asian,2.51,2018,27,4.2,NaN
2686,"Infant, neonatal, postneonatal, fetal, and per...",1,"Perinatal deaths per 1,000 live births plus la...",6,Race and Hispanic origin (Single race),4,Not Hispanic or Latina: Native Hawaiian or Oth...,2.52,2017,26,NaN,...
2687,"Infant, neonatal, postneonatal, fetal, and per...",1,"Perinatal deaths per 1,000 live births plus la...",6,Race and Hispanic origin (Single race),4,Not Hispanic or Latina: Native Hawaiian or Oth...,2.52,2018,27,11.4,NaN

In [16]:
import matplotlib.pyplot as plt
import numpy as np

In [17]:
MatHealth.plot(x = 'Year', y = 'Estimate', kind='bar')

KeyError: 'Year'